apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  labels:
    {{- include "spring-boot-chart.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envs.config | nindent 2 }}
