apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  labels:
    {{- include "spring-boot-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "spring-boot-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "spring-boot-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spring-boot-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "spring-boot-chart.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
           - name: config-volume
             mountPath: /sprinb-boot/config
          env:
          - name: SPRING_CONFIG_LOCATION
            value: "/sprinb-boot/config/"
          
          envFrom:
            {{- if .Values.existingConfigMap }}
            - configMapRef:
                name: {{ .Values.existingConfigMap }}
            {{- end }}
            - configMapRef:
                name: {{ include "spring-boot-chart.fullname" . }}
            {{- if .Values.existingSecret }}
            - secretRef:
                name: {{ .Values.existingSecret }}
            {{- end }}
            - secretRef:
                name: {{ include "spring-boot-chart.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              #{{- $contextPath := .Values.envs.config.SERVER_SERVLET_CONTEXT_PATH | default "/actuator/health/liveness" | printf "%s/" | urlParse }}
              #path: {{ get $contextPath "path" }}
              path: /actuator/health/livenessState 
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              #{{- $contextPath := .Values.envs.config.SERVER_SERVLET_CONTEXT_PATH | default "/actuator/health/readiness" | printf "%s/" | urlParse }}
              #path: {{ get $contextPath "path" }}
              path: /actuator/health/readinessState
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
