apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-chart.fullname" . }}
  labels:
    {{- include "spring-boot-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.envs.secret | nindent 2 }}